# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a07c0975c49e9af544474c9ddb59c30bc9f14aeb681137692182ccab4d7d8167d712251757210fc343eb87b285b84d0f641a52e32645b997bef3641dea68ed7

test:
  secret_key_base: 9efea85e1d1918a785190f80a858db0a4a4b3dc9804743c8e1b9f7da67bc186a907f26ff8bc7af212fd2db1b44daaa7bc5fc0aca1f236d4c481833539aa1565b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
